### ISSUE TITLE
api/studies/{studyName}/users distinguer admin/supervisor

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#259]
Besoin des infos des users pour admin

**Comment by salimkanoun** [comment]
@EmilieOLIVIE j'ai ajouté les details user pour l'admin
L'appel de route doit avoir le querytag ?role pour demander les details ou pas

/api/studies/' . $study->name . '/users?role=Administrator

/api/studies/' . $study->name . '/users?role=Supervisor
