### ISSUE TITLE
Infos supplémentaires pour module de stats

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#263]
Exposer:
-center 
-country
-reviewerName 
Dans getVisitsFromVisitType

+ type des données pour les champs des formulaires investigator / reviewer ?

**Comment by salimkanoun** [comment]
@EmilieOLIVIE j'ai ajouter CenterName et CountryCode dans une sous clé  de l'api GetVisitsFromVisitType

Pour les reviewerName, il faut appeler l'autre API 
studies/{studyName}/visit-types/{visitTypeId}/review-progression
Qui donne pour chaque visit qui a fait et qui a pas fait, je sais pas si y a les info que tu veux la dessus.

Et je t'ai ouvert 2 API pour avoir les metadata des fomulaire pour connaitre les types de champs
    Route::get('studies/{studyName}/visit-types/{visitTypeId}/reviews/metadata', [StudyController::class, 'getReviewsMetadataFromVisitType'] );
Route::get('studies/{studyName}/visit-types/{visitTypeId}/investigator-forms/metadata', [StudyController::class, 'getInvestigatorFormsMetadataFromVisitType'] );
