### ISSUE TITLE
Delete Documentation A passer en soft delete

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO#265]

**Comment by salimkanoun** [comment]
+ reactivate

**Comment by salimkanoun** [comment]
@EmilieOLIVIE 
J'ai ouvert une route
Route::patch('documentations/{id}/reactivate', [DocumentationController::class, 'reactivateDocumentation'] );

Tu peux faire l'intégration front ? Suffit de faire un toogle delete / reactivate pour le supervisor au niveau de la table de documentation.
Ici pas besoin de reason

+ J'ai crée une nouvelle clé tracker qu'il faut lister dans le tracker supervisor qui est "Reactivate Documentation"

**Comment by EmilieOLIVIE** [comment]
Ajusté dans le front
