### ISSUE TITLE
createUserTest not passing

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#289]
createCorrectPayload
createAlreadyExistingUser
createAlreadyExistingEmail
createInvalidPhone
createNoOrthancAddress
createNoOrthancLogin
createNoOrthancPassword

`Class "libphonenumber\PhoneNumberUtil" not found`

**Comment by salimkanoun** [comment]
Faut faire composer install

Le ven. 13 août 2021 à 15:13, EmilieOLIVIE ***@***.***> a
écrit :

**Comment by EmilieOLIVIE** [comment]
Effectivement, ça marche mieux comme ça..! :see_no_evil:
