### ISSUE TITLE
Création users par supervisors

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#359]

**Comment by salimkanoun** [comment]
Dans backend
passer role et studyname en qeury tag
check permission si supervisor
autoriser creation d'user
definition de role mais que dans l'étude du supervisot

Dans le front
Dans le menu "users" du supervisor
Ajout barre de recherche par email qui répond connu ou pas connu
Si connu => récupérer ID et proposer d'affeter role dans l'étude courante
Si inconnu => form de creation et d'affectation de role
