### ISSUE TITLE
SendMail mail de l'émetteur pas en copie

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#455]
> Si on envoie un mail depuis GaelO, serait-il possible de mettre l'utilisateur qui envoie le mail en emetteur du mail (ou au moins en copie) ? Pour que le destinataire puisse répondre directement

> Je vois aucun mail en copie

**Comment by salimkanoun** [comment]
Dans mail interface tu a setReplyTo pour mettre le destinataire en réponse 

Faut pas changer l émetteur du mail pour pas augmenter les problème de spam.
Par contre tu peux mettre le user d origine en copie pour qu'il ait un feedback que le mail est bien parti

**Comment by salimkanoun** [comment]
Good !
