### ISSUE TITLE
Reviewer form contraintes vérfiées même en non validated

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#464]
> Reviewer: Draft ne semble pas fonctionner: message d'erreur "Review Form Validation Failed"

Les contraintes sont vérifiées pour le formulaire reviewer malgré un `validated:false` (le draft du formulaire investigateur fonctionne, lui).

**Comment by salimkanoun** [comment]
Devrait etre fixé, a noter toute les clés du formulaire doivent etre transmise au back (avec null si elle sont unset) (mais je crois que c'est déjà le cas)
