### ISSUE TITLE
Suggestion pour le Workflow Manager: Possibilité d'éditer les statuts des visites en "Should be done"

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#513]

**Comment by ClaraAtn** [comment]
Par exemple si on apprend un décalage du ttt et donc de l'examen ou si examen indiqué comme n'ayant pas été réalisé (à la limite pour non réalisé on peut créer en not done mais pour décalage, actuellement pas possible de l'indiquer dans WF Manager) - ou alors ajouter une notion de date théorique (la "should be done") et une date éditable par le supervisor et prendre par défaut "should be done" et l'éditable si non vide ?

**Comment by salimkanoun** [comment]
On voit pas trop de solution à ce probleme car les statut que tu vois sont calculés à la volée et ne sont pas stockés en base de donnée (si on se met à stocker ces informations ca veut dire qu'on devient un CRF clinique ...)

Le seul truc possible que je vois serait d'introduire des shift sur la base d'un fichier csv qui donnerait les shift de chaque pour rafraichir les statuts (et qu'il faudrait importer à chaque fois)

Ou alors stocker le shift dans le metadadonée des patients

Mais tout ca est lourd à implementer, on peut pas se lancer la dessus à court / moyen terme

**Comment by ClaraAtn** [comment]
Ok tant pis, on va devoir conserver nos tableaux de suivi en parallèle alors ;)
