### ISSUE TITLE
Workflow Manager: pour le Visits Overview Reviews, la liste affiche toutes les visites, pas uniquement celles en attente de relecture

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#514]

**Comment by salimkanoun** [comment]
Probalement à faire via un multiselect coté front avec une function reverse pour pouvoir filter les visites qui ne sont PAS en review done (ndlr : tous sauf les review done)

**Comment by salimkanoun** [comment]
dupliqué dans gaelo issue (fermé ici)
