### ISSUE TITLE
Mail QcReport (cf détails)

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#517]
- [x] Mettre "QC Report" au lieu de "QcReport" dans l'Objet du mail :)
- [x] Les éléments du mail sont centrés mais pas adaptés à la taille de la fenêtre, du coup on est obligé de scroller droite/gauche => Ok pour moi pourtant meme sur smartphone
- [x] Le titre Study Infos est pas au milieu des 2 barres => ? Semble OK
- [x] Les 2 barres sont d'épaisseurs différentes
- [ ] ça pourrait être bien de mettre un petit warning si "Visit Date" est différente de "Acquisition Date" (signe qu'on doit faire une modification au niveau Supervisor ou qu'il y a eu une erreur de chargement), si c'est possible
- [x] Peut-on également ajouter la date de registration et la date théorique de la visite ? (les should be done before/after), ça permettrait de vérifier que les images sont bien chargées dans la bonne visite
- [x] Dans patient height on a le numéro patient
- [x] Pour le "It's all good", ça gère bien si la visite a déjà été contrôlée par un user mais pas pour le "See in GaelO" (on a oops something went wrong...)
- [x] Remettre le stripped pour les table
- [x] Double envoi de report à investiger
- [x] Reste 2 warning dans sonarcloud

**Comment by salimkanoun** [comment]
Pour l'investigation form, on pourrait l'afficher comme sur GaelO ? ou d'une manière un peu plus user friendly ? :) => Non pas possible, on peut pas porter l'investigateur form dans le mail.
On peut par contre mettre un tableau si tu préfères @ClaraAtn

**Comment by ClaraAtn** [comment]
Oui un petit tableau ce serait bien :)

**Comment by salimkanoun** [comment]
la plupart des probleme sont fix, 
le reste est passé à https://github.com/Pixilib/GaelO/issues/523
