### ISSUE TITLE
Statistics: Pour QC Time, si on filtre sur QC with corrective action, ça n'a pas l'air de fonctionner

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#519]
Dans ce graphe, on doit avoir le temps entre le premier chargement avant demande d'action corrective et le QC accepted ou refused c'est bien ça ?

Je ne vois rien apparaitre, ni si on a une action corrective en attente ni si on a une action corrective résolue

**Comment by EmilieOLIVIE** [comment]
> Dans ce graphe, on doit avoir le temps entre le premier chargement avant demande d'action corrective et le QC accepted ou refused c'est bien ça ?

C'est ça :+1:

> Je ne vois rien apparaitre, ni si on a une action corrective en attente ni si on a une action corrective résolue

Lié au problème du QC Time négatif (en mettant une tolérance négative comme -15, il apparait) ; corrigé dans https://github.com/Pixilib/GaelO_Frontend/issues/1053
