### ISSUE TITLE
Gérer review needed/not needed pour les études ancillaires

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#534]

**Comment by salimkanoun** [comment]
Pas simple à gérer,
=> soit continuer à chercher (dans la nouvelle branche)
=> soit laisser les visites considérée comme available si le QC est passé (ou not needed) et se servir d'un filtrage coté front (ou faire des seteur via api)
=> Evaluer l'interet de mettre review_available a null pour expliciter que ce statut n'est pas set

**Comment by salimkanoun** [comment]
modifier le review available des autres visite quand on traite la réponse d'un forumulaire d'une étude ancillaire
