### ISSUE TITLE
GetVisit forbidden pour les reviewers études ancillaires

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#539]
`        if ($requestedRole === Constants::ROLE_REVIEWER) {
            //Check parent patient allowed and has one awaiting review visit
            return $this->authorizationPatientService->isPatientAllowed($requestedRole) && $this->visitRepositoryInterface->isParentPatientHavingOneVisitAwaitingReview($this->visitId, $this->patientStudy, $this->userId);
        } else if ($requestedRole === Constants::ROLE_CONTROLLER) {
`
Dans AuthorizationVisitService

**Comment by salimkanoun** [comment]
Devrait etre résolu (fermer issue si ok)

**Comment by EmilieOLIVIE** [comment]
Pas résolu (`isParentPatientHavingOneVisitAwaitingReview` renvoie toujours `false` dans `AuthorizationVisitService`).

**Comment by EmilieOLIVIE** [comment]
Idem pour le getDicoms qui renvoie un 403

**Comment by salimkanoun** [comment]
oui je vois le souci (c'est le meme que pour visit) je m'en occupe

**Comment by salimkanoun** [comment]
@EmilieOLIVIE devrait etre bon cette fois

**Comment by EmilieOLIVIE** [comment]
All good.
