### ISSUE TITLE
getVisitsInStudy renvoie les review status de l'étude princeps

### ISSUE THREAD

**Issue by EmilieOLIVIE** [Pixilib/GaelO#540]

**Comment by salimkanoun** [comment]
Devrait etre OK, issue a fermer si c'est bien bon

**Comment by EmilieOLIVIE** [comment]
OK pour le getVisitsInStudy ; le `getPatientVisit` (appelé dans le panneau superviseur dans l'onglet "Visits") et `getVisitsFromStudy` (appelé dans le Workflow Manager) ont le même problème (ils renvoie les visites avec reviews en `Not Needed`)

**Comment by salimkanoun** [comment]
j'ai fix pour getVisitsFromStudy mais pour getPatientVisit je vois pas le bug à reverifier @EmilieOLIVIE

**Comment by EmilieOLIVIE** [comment]
Effectivement, tout a l'air bon.
