### ISSUE TITLE
Viewer: Stone (Patient) affiche toutes les visites avec des séries chargées pour le patient (pas uniquement celles acceptées au QC) pour le reviewer

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#565]

**Comment by salimkanoun** [comment]
Ca vas pas etre possible de modifier cela, le listing des ressources dans Stone et OHIF est consommé depuis DicomWeb, le serveur dicom va lister toutes les ressources, y compris les non QC et y compris les envoi deleted.
les envoi deleted vont etre listé mais les images vont par contre pas etre accessible. 

Le probleme est que ces viewer appellent directement les ressource dicom sans que je puisse les controller reelment, il faudrait modifier le viewer pour que nous soit trnsmis le visit id qui justifie l'appel.

Il n'y aura pas de solutions parfaites à ce probleme et c'est trop lourd à mettre en place pour l'instant
