### ISSUE TITLE
FRCONNECT: Reviewer: si number of new lesions est < 0, il ne faudrait pas obligatoirement que DS = 5 ? (autre DS accepté)

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#567]

**Comment by salimkanoun** [comment]
Non on a dit qu'on ne manipulait plus le formulaire,
On laisse le formulaire "libre" par contre on verifie les incohérence au moment de l'envoi et si y a des new lesiosn avec un DS different de 5 on bloque l'envoi et demande à l'utilisateur de se corriger.

ca crée moins de probleme d'état du formulaire de proceder à une post validation plutot que manipuler le formulaire à priori (c'est faisable quand t'a un seul composant qui commande un autre mais avec Lugano / DS / Newleison qui se répercutent l'un l'autre c'est l'enfer)
