### ISSUE TITLE
Investigator: une fois qu'un QC est fait, l'investigateur ne peut plus supprimer/réactiver de séries (tout bon) mais par contre il ne peut plus visualiser le détail des séries chargées. Pourrait-on faire apparaitre les détails ?

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#589]

**Comment by ClaraAtn** [comment]
![Image](https://user-images.githubusercontent.com/29735176/208473559-62b81626-ddda-4f93-9ba9-1a3a5b582374.png)

**Comment by ClaraAtn** [comment]
Ah zut... en fait, j'ai fait un delete all en investigator, mais du coup pas la possibilité de reactivate all, les séries disparaissent. Je suis allée sur le profil supervisor pour reactiver la study dans upload mais effectivement ça n'a pas réactivé les séries, faut cliquer une deuxième fois sur reactivate all, j'avais pas vu, sorry...
Je ne sais pas s'il faudrait pas laisser la possibilité à l'investigator de réactiver tout aussi sans faire disparaitre si toutes les séries sont delete

**Comment by salimkanoun** [comment]
Il faudrait afficher a l investigateur Les study envoyé qu'il a reset et si il y en a plusieurs il faudrait qu'il choisisse lui même la bonne à réactiver... Ça fait beaucoup de complexité à la charge de l investigateur

**Comment by ClaraAtn** [comment]
Ok pas de souci, on laisse comme ça alors, ça ne devrait pas poser de souci !
