### ISSUE TITLE
Connection: Lors d'une connexion avec un compte qui n'a qu'une étude, une étude non attribuée à ce compte a été sélectionnée par défaut

### ISSUE THREAD

**Issue by ClaraAtn** [Pixilib/GaelO#590]

**Comment by ClaraAtn** [comment]
(Compte aryasvitkona1@gmail.com)

Si je mets déconnecte puis reconnecte sur ce compte, le problème ne réapparait pas

**Comment by salimkanoun** [comment]
C'est parceque tu demande l url qui contient /study/BICAR
Le front tente d afficher bicar car tu lui demande spécifiquement cette étude mais il n'y arrivera pas car le serveur va répondre que l accès est interdit (d'où le popup d erreur)

**Comment by ClaraAtn** [comment]
Oula oui mince, j'avais pas vu ça, désolée !
